### List all messages
GET http://localhost:3000/messages HTTP/1.1

### Get specific message

GET http://localhost:3000/messages/123?hi=Im-saying-hi HTTP/1.1

### Create a new message

POST http://localhost:3000/messages HTTP/1.1
content-type: application/json

{
    "content": "hello"
}